### ISSUE TITLE
your feelings are valid 

### ISSUE THREAD

**Issue by avplu** [altude/altude#2]
@altude i noticed your recent posts on your github repo and i just wanted to let you know that your struggles are valid, your feelings are valid, and you are valid. i also want you to know you are loved and seen. your friends and i all miss you, we love you, and we care about you. 
if you are considering suicide, please reconsider. we will miss you so much. 

if you need anyone to talk to, i'm always here 

you can talk to me via the following contact methods: 
@alexkbwi on Twitter 
alexkbwi#4718 on Discord 
954-401-6690 on WhatsApp, SMS/MMS/RCS, Telegram, and Skype
@alex_plumey on Instagram 
alexplumey@outlook.com for email and Skype 
spiritualpick@gmail.com for Google Chat

**Comment by altude** [comment]
ty
